name: Secret Scanning

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run truffleHog
      run: |
        python3 -m venv env
        source env/bin/activate
        python -m pip install truffleHog
        python env/bin/trufflehog https://github.com/youngowl13/pepper.git || true
        ls 
        pwd
        
    - name: Run detect-secrets
      run: |
        python3 -m venv env-ds
        source env-ds/bin/activate
        pip install detect-secrets
        detect-secrets scan > detect-secrets.json
        ls
        pwd
      
 
