name: Secret Scanning

on: [push]

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python and pip
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Install TruffleHog from source
        run: pip3 install trufflehog

      - name: Run TruffleHog against the repository
        run: trufflehog --json . > trufflehog_output.json

      - name: Upload JSON Report
        uses: actions/upload-artifact@v2
        with:
          name: secret-scan-report
          path: trufflehog_output.json
